sudo: required

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.23.2

before_install:
  # install docker compose to support docker compose 3.7+ on Travis
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

# should not be needed anymore, since all images are now on Dockerhub
#install:
#  - chmod +x build-images.sh
#  - ./build-images.sh

script:
  # ampersand is required to run the workers in the background -> don't block the main travis thread
  - docker-compose up --scale spark-worker=3 & 
  # wait until the workers are up
  - sleep 20 
  - docker ps
  - docker network ls
  # run scala pi
  - cd spark-submit && chmod +x local_scala_pi.sh && ./local_scala_pi.sh 
  # run python pi
  - chmod +x local_python_pi.sh && ./local_python_pi.sh 

notifications:
  email:
    recipients:
      - lukas.heumos@student.uni-tuebingen.de
    on_success: never 
    on_failure: always 
  


