version: "3.7"
services:
  spark-master:
    image: qbic/spark:latest_master
    container_name: spark-master
    hostname: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    networks:
      - spark-network
    environment:
      - "SPARK_LOCAL_IP=spark-master"
      - "SPARK_MASTER_PORT=7077"
      - "SPARK_MASTER_WEBUI_PORT=8080"
    volumes:
      - /mnt/spark-apps:/opt/spark-apps
      - /mnt/spark-data:/opt/spark-data
    command: "/start-master.sh"
  spark-worker:
    image: qbic/spark:latest_worker
    depends_on:
      - spark-master
    ports:
      - 8080
    networks:
      - spark-network
    env_file: ./env/spark-worker.sh
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "SPARK_WORKER_WEBUI_PORT=8080"
    command: "/start-worker.sh"
networks:
  spark-network:
    driver: bridge
    ipam:
      driver: default
